/* Generated By:JavaCC: Do not edit this line. AnalyseurSyntaxiqueConstants.java */
package fr.insarouen.iti.compilation.lightgrep.analyseurs;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalyseurSyntaxiqueConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CARACTERE_ECHAPE = 1;
  /** RegularExpression Id. */
  int OU = 2;
  /** RegularExpression Id. */
  int PARAG = 3;
  /** RegularExpression Id. */
  int PARAD = 4;
  /** RegularExpression Id. */
  int CROCHETG = 5;
  /** RegularExpression Id. */
  int CROCHETD = 6;
  /** RegularExpression Id. */
  int ZERO_N = 7;
  /** RegularExpression Id. */
  int ZERO_UN = 8;
  /** RegularExpression Id. */
  int UN_N = 9;
  /** RegularExpression Id. */
  int JOKER = 10;
  /** RegularExpression Id. */
  int TIRET = 11;
  /** RegularExpression Id. */
  int CIRCONFLEXE = 12;
  /** RegularExpression Id. */
  int FIN_DE_LIGNE = 13;
  /** RegularExpression Id. */
  int CARACTERE = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CARACTERE_ECHAPE>",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\"?\"",
    "\"+\"",
    "\".\"",
    "\"-\"",
    "\"^\"",
    "\"$\"",
    "<CARACTERE>",
  };

}
